databases:
  - name: university-mysql
    databaseName: university_t3cc
    plan: free

services:
  # Backend API Service
  - type: web
    name: university-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DB_HOST
        fromDatabase:
          name: university-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: university-mysql
          property: port
      - key: DB_NAME
        fromDatabase:
          name: university-mysql
          property: database
      - key: DB_USER
        fromDatabase:
          name: university-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: university-mysql
          property: password
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /actuator/health

  # Frontend Web Service
  - type: web
    name: university-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://university-backend-ygsl.onrender.com